// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ad.proto

package cn.beckbi.pb;

public final class AdInfo {
  private AdInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Ad)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description = 3;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>float price = 4;</code>
     */
    float getPrice();
  }
  /**
   * Protobuf type {@code Ad}
   */
  public  static final class Ad extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Ad)
      AdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Ad.newBuilder() to construct.
    private Ad(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ad() {
      id_ = 0;
      name_ = "";
      description_ = "";
      price_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Ad(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 37: {

              price_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.beckbi.pb.AdInfo.internal_static_Ad_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.beckbi.pb.AdInfo.internal_static_Ad_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.beckbi.pb.AdInfo.Ad.class, cn.beckbi.pb.AdInfo.Ad.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    private float price_;
    /**
     * <code>float price = 4;</code>
     */
    public float getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
      }
      if (price_ != 0F) {
        output.writeFloat(4, price_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
      }
      if (price_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.beckbi.pb.AdInfo.Ad)) {
        return super.equals(obj);
      }
      cn.beckbi.pb.AdInfo.Ad other = (cn.beckbi.pb.AdInfo.Ad) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && (
          java.lang.Float.floatToIntBits(getPrice())
          == java.lang.Float.floatToIntBits(
              other.getPrice()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPrice());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.beckbi.pb.AdInfo.Ad parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.beckbi.pb.AdInfo.Ad parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.Ad parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.beckbi.pb.AdInfo.Ad parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.Ad parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.beckbi.pb.AdInfo.Ad parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.Ad parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.beckbi.pb.AdInfo.Ad parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.Ad parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.beckbi.pb.AdInfo.Ad parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.Ad parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.beckbi.pb.AdInfo.Ad parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.beckbi.pb.AdInfo.Ad prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Ad}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Ad)
        cn.beckbi.pb.AdInfo.AdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.beckbi.pb.AdInfo.internal_static_Ad_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.beckbi.pb.AdInfo.internal_static_Ad_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.beckbi.pb.AdInfo.Ad.class, cn.beckbi.pb.AdInfo.Ad.Builder.class);
      }

      // Construct using cn.beckbi.pb.AdInfo.Ad.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        description_ = "";

        price_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.beckbi.pb.AdInfo.internal_static_Ad_descriptor;
      }

      public cn.beckbi.pb.AdInfo.Ad getDefaultInstanceForType() {
        return cn.beckbi.pb.AdInfo.Ad.getDefaultInstance();
      }

      public cn.beckbi.pb.AdInfo.Ad build() {
        cn.beckbi.pb.AdInfo.Ad result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.beckbi.pb.AdInfo.Ad buildPartial() {
        cn.beckbi.pb.AdInfo.Ad result = new cn.beckbi.pb.AdInfo.Ad(this);
        result.id_ = id_;
        result.name_ = name_;
        result.description_ = description_;
        result.price_ = price_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.beckbi.pb.AdInfo.Ad) {
          return mergeFrom((cn.beckbi.pb.AdInfo.Ad)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.beckbi.pb.AdInfo.Ad other) {
        if (other == cn.beckbi.pb.AdInfo.Ad.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.getPrice() != 0F) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.beckbi.pb.AdInfo.Ad parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.beckbi.pb.AdInfo.Ad) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 3;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private float price_ ;
      /**
       * <code>float price = 4;</code>
       */
      public float getPrice() {
        return price_;
      }
      /**
       * <code>float price = 4;</code>
       */
      public Builder setPrice(float value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float price = 4;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Ad)
    }

    // @@protoc_insertion_point(class_scope:Ad)
    private static final cn.beckbi.pb.AdInfo.Ad DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.beckbi.pb.AdInfo.Ad();
    }

    public static cn.beckbi.pb.AdInfo.Ad getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ad>
        PARSER = new com.google.protobuf.AbstractParser<Ad>() {
      public Ad parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ad(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Ad> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ad> getParserForType() {
      return PARSER;
    }

    public cn.beckbi.pb.AdInfo.Ad getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AdListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AdList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string createAt = 1;</code>
     */
    java.lang.String getCreateAt();
    /**
     * <code>string createAt = 1;</code>
     */
    com.google.protobuf.ByteString
        getCreateAtBytes();

    /**
     * <code>string traceId = 2;</code>
     */
    java.lang.String getTraceId();
    /**
     * <code>string traceId = 2;</code>
     */
    com.google.protobuf.ByteString
        getTraceIdBytes();

    /**
     * <code>repeated .Ad ads = 3;</code>
     */
    java.util.List<cn.beckbi.pb.AdInfo.Ad> 
        getAdsList();
    /**
     * <code>repeated .Ad ads = 3;</code>
     */
    cn.beckbi.pb.AdInfo.Ad getAds(int index);
    /**
     * <code>repeated .Ad ads = 3;</code>
     */
    int getAdsCount();
    /**
     * <code>repeated .Ad ads = 3;</code>
     */
    java.util.List<? extends cn.beckbi.pb.AdInfo.AdOrBuilder> 
        getAdsOrBuilderList();
    /**
     * <code>repeated .Ad ads = 3;</code>
     */
    cn.beckbi.pb.AdInfo.AdOrBuilder getAdsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code AdList}
   */
  public  static final class AdList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AdList)
      AdListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdList.newBuilder() to construct.
    private AdList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdList() {
      createAt_ = "";
      traceId_ = "";
      ads_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              createAt_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              traceId_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                ads_ = new java.util.ArrayList<cn.beckbi.pb.AdInfo.Ad>();
                mutable_bitField0_ |= 0x00000004;
              }
              ads_.add(
                  input.readMessage(cn.beckbi.pb.AdInfo.Ad.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          ads_ = java.util.Collections.unmodifiableList(ads_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.beckbi.pb.AdInfo.internal_static_AdList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.beckbi.pb.AdInfo.internal_static_AdList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.beckbi.pb.AdInfo.AdList.class, cn.beckbi.pb.AdInfo.AdList.Builder.class);
    }

    private int bitField0_;
    public static final int CREATEAT_FIELD_NUMBER = 1;
    private volatile java.lang.Object createAt_;
    /**
     * <code>string createAt = 1;</code>
     */
    public java.lang.String getCreateAt() {
      java.lang.Object ref = createAt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createAt_ = s;
        return s;
      }
    }
    /**
     * <code>string createAt = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCreateAtBytes() {
      java.lang.Object ref = createAt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRACEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object traceId_;
    /**
     * <code>string traceId = 2;</code>
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      }
    }
    /**
     * <code>string traceId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADS_FIELD_NUMBER = 3;
    private java.util.List<cn.beckbi.pb.AdInfo.Ad> ads_;
    /**
     * <code>repeated .Ad ads = 3;</code>
     */
    public java.util.List<cn.beckbi.pb.AdInfo.Ad> getAdsList() {
      return ads_;
    }
    /**
     * <code>repeated .Ad ads = 3;</code>
     */
    public java.util.List<? extends cn.beckbi.pb.AdInfo.AdOrBuilder> 
        getAdsOrBuilderList() {
      return ads_;
    }
    /**
     * <code>repeated .Ad ads = 3;</code>
     */
    public int getAdsCount() {
      return ads_.size();
    }
    /**
     * <code>repeated .Ad ads = 3;</code>
     */
    public cn.beckbi.pb.AdInfo.Ad getAds(int index) {
      return ads_.get(index);
    }
    /**
     * <code>repeated .Ad ads = 3;</code>
     */
    public cn.beckbi.pb.AdInfo.AdOrBuilder getAdsOrBuilder(
        int index) {
      return ads_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCreateAtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, createAt_);
      }
      if (!getTraceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, traceId_);
      }
      for (int i = 0; i < ads_.size(); i++) {
        output.writeMessage(3, ads_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCreateAtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, createAt_);
      }
      if (!getTraceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, traceId_);
      }
      for (int i = 0; i < ads_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, ads_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.beckbi.pb.AdInfo.AdList)) {
        return super.equals(obj);
      }
      cn.beckbi.pb.AdInfo.AdList other = (cn.beckbi.pb.AdInfo.AdList) obj;

      boolean result = true;
      result = result && getCreateAt()
          .equals(other.getCreateAt());
      result = result && getTraceId()
          .equals(other.getTraceId());
      result = result && getAdsList()
          .equals(other.getAdsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CREATEAT_FIELD_NUMBER;
      hash = (53 * hash) + getCreateAt().hashCode();
      hash = (37 * hash) + TRACEID_FIELD_NUMBER;
      hash = (53 * hash) + getTraceId().hashCode();
      if (getAdsCount() > 0) {
        hash = (37 * hash) + ADS_FIELD_NUMBER;
        hash = (53 * hash) + getAdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.beckbi.pb.AdInfo.AdList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.beckbi.pb.AdInfo.AdList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.AdList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.beckbi.pb.AdInfo.AdList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.AdList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.beckbi.pb.AdInfo.AdList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.AdList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.beckbi.pb.AdInfo.AdList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.AdList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.beckbi.pb.AdInfo.AdList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.AdList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.beckbi.pb.AdInfo.AdList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.beckbi.pb.AdInfo.AdList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AdList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AdList)
        cn.beckbi.pb.AdInfo.AdListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.beckbi.pb.AdInfo.internal_static_AdList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.beckbi.pb.AdInfo.internal_static_AdList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.beckbi.pb.AdInfo.AdList.class, cn.beckbi.pb.AdInfo.AdList.Builder.class);
      }

      // Construct using cn.beckbi.pb.AdInfo.AdList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAdsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        createAt_ = "";

        traceId_ = "";

        if (adsBuilder_ == null) {
          ads_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          adsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.beckbi.pb.AdInfo.internal_static_AdList_descriptor;
      }

      public cn.beckbi.pb.AdInfo.AdList getDefaultInstanceForType() {
        return cn.beckbi.pb.AdInfo.AdList.getDefaultInstance();
      }

      public cn.beckbi.pb.AdInfo.AdList build() {
        cn.beckbi.pb.AdInfo.AdList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.beckbi.pb.AdInfo.AdList buildPartial() {
        cn.beckbi.pb.AdInfo.AdList result = new cn.beckbi.pb.AdInfo.AdList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.createAt_ = createAt_;
        result.traceId_ = traceId_;
        if (adsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            ads_ = java.util.Collections.unmodifiableList(ads_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.ads_ = ads_;
        } else {
          result.ads_ = adsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.beckbi.pb.AdInfo.AdList) {
          return mergeFrom((cn.beckbi.pb.AdInfo.AdList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.beckbi.pb.AdInfo.AdList other) {
        if (other == cn.beckbi.pb.AdInfo.AdList.getDefaultInstance()) return this;
        if (!other.getCreateAt().isEmpty()) {
          createAt_ = other.createAt_;
          onChanged();
        }
        if (!other.getTraceId().isEmpty()) {
          traceId_ = other.traceId_;
          onChanged();
        }
        if (adsBuilder_ == null) {
          if (!other.ads_.isEmpty()) {
            if (ads_.isEmpty()) {
              ads_ = other.ads_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAdsIsMutable();
              ads_.addAll(other.ads_);
            }
            onChanged();
          }
        } else {
          if (!other.ads_.isEmpty()) {
            if (adsBuilder_.isEmpty()) {
              adsBuilder_.dispose();
              adsBuilder_ = null;
              ads_ = other.ads_;
              bitField0_ = (bitField0_ & ~0x00000004);
              adsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAdsFieldBuilder() : null;
            } else {
              adsBuilder_.addAllMessages(other.ads_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.beckbi.pb.AdInfo.AdList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.beckbi.pb.AdInfo.AdList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object createAt_ = "";
      /**
       * <code>string createAt = 1;</code>
       */
      public java.lang.String getCreateAt() {
        java.lang.Object ref = createAt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          createAt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string createAt = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCreateAtBytes() {
        java.lang.Object ref = createAt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createAt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string createAt = 1;</code>
       */
      public Builder setCreateAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string createAt = 1;</code>
       */
      public Builder clearCreateAt() {
        
        createAt_ = getDefaultInstance().getCreateAt();
        onChanged();
        return this;
      }
      /**
       * <code>string createAt = 1;</code>
       */
      public Builder setCreateAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createAt_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object traceId_ = "";
      /**
       * <code>string traceId = 2;</code>
       */
      public java.lang.String getTraceId() {
        java.lang.Object ref = traceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          traceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string traceId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTraceIdBytes() {
        java.lang.Object ref = traceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          traceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string traceId = 2;</code>
       */
      public Builder setTraceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        traceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string traceId = 2;</code>
       */
      public Builder clearTraceId() {
        
        traceId_ = getDefaultInstance().getTraceId();
        onChanged();
        return this;
      }
      /**
       * <code>string traceId = 2;</code>
       */
      public Builder setTraceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        traceId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<cn.beckbi.pb.AdInfo.Ad> ads_ =
        java.util.Collections.emptyList();
      private void ensureAdsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          ads_ = new java.util.ArrayList<cn.beckbi.pb.AdInfo.Ad>(ads_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.beckbi.pb.AdInfo.Ad, cn.beckbi.pb.AdInfo.Ad.Builder, cn.beckbi.pb.AdInfo.AdOrBuilder> adsBuilder_;

      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public java.util.List<cn.beckbi.pb.AdInfo.Ad> getAdsList() {
        if (adsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ads_);
        } else {
          return adsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public int getAdsCount() {
        if (adsBuilder_ == null) {
          return ads_.size();
        } else {
          return adsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public cn.beckbi.pb.AdInfo.Ad getAds(int index) {
        if (adsBuilder_ == null) {
          return ads_.get(index);
        } else {
          return adsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public Builder setAds(
          int index, cn.beckbi.pb.AdInfo.Ad value) {
        if (adsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdsIsMutable();
          ads_.set(index, value);
          onChanged();
        } else {
          adsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public Builder setAds(
          int index, cn.beckbi.pb.AdInfo.Ad.Builder builderForValue) {
        if (adsBuilder_ == null) {
          ensureAdsIsMutable();
          ads_.set(index, builderForValue.build());
          onChanged();
        } else {
          adsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public Builder addAds(cn.beckbi.pb.AdInfo.Ad value) {
        if (adsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdsIsMutable();
          ads_.add(value);
          onChanged();
        } else {
          adsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public Builder addAds(
          int index, cn.beckbi.pb.AdInfo.Ad value) {
        if (adsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdsIsMutable();
          ads_.add(index, value);
          onChanged();
        } else {
          adsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public Builder addAds(
          cn.beckbi.pb.AdInfo.Ad.Builder builderForValue) {
        if (adsBuilder_ == null) {
          ensureAdsIsMutable();
          ads_.add(builderForValue.build());
          onChanged();
        } else {
          adsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public Builder addAds(
          int index, cn.beckbi.pb.AdInfo.Ad.Builder builderForValue) {
        if (adsBuilder_ == null) {
          ensureAdsIsMutable();
          ads_.add(index, builderForValue.build());
          onChanged();
        } else {
          adsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public Builder addAllAds(
          java.lang.Iterable<? extends cn.beckbi.pb.AdInfo.Ad> values) {
        if (adsBuilder_ == null) {
          ensureAdsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ads_);
          onChanged();
        } else {
          adsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public Builder clearAds() {
        if (adsBuilder_ == null) {
          ads_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          adsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public Builder removeAds(int index) {
        if (adsBuilder_ == null) {
          ensureAdsIsMutable();
          ads_.remove(index);
          onChanged();
        } else {
          adsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public cn.beckbi.pb.AdInfo.Ad.Builder getAdsBuilder(
          int index) {
        return getAdsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public cn.beckbi.pb.AdInfo.AdOrBuilder getAdsOrBuilder(
          int index) {
        if (adsBuilder_ == null) {
          return ads_.get(index);  } else {
          return adsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public java.util.List<? extends cn.beckbi.pb.AdInfo.AdOrBuilder> 
           getAdsOrBuilderList() {
        if (adsBuilder_ != null) {
          return adsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ads_);
        }
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public cn.beckbi.pb.AdInfo.Ad.Builder addAdsBuilder() {
        return getAdsFieldBuilder().addBuilder(
            cn.beckbi.pb.AdInfo.Ad.getDefaultInstance());
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public cn.beckbi.pb.AdInfo.Ad.Builder addAdsBuilder(
          int index) {
        return getAdsFieldBuilder().addBuilder(
            index, cn.beckbi.pb.AdInfo.Ad.getDefaultInstance());
      }
      /**
       * <code>repeated .Ad ads = 3;</code>
       */
      public java.util.List<cn.beckbi.pb.AdInfo.Ad.Builder> 
           getAdsBuilderList() {
        return getAdsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.beckbi.pb.AdInfo.Ad, cn.beckbi.pb.AdInfo.Ad.Builder, cn.beckbi.pb.AdInfo.AdOrBuilder> 
          getAdsFieldBuilder() {
        if (adsBuilder_ == null) {
          adsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.beckbi.pb.AdInfo.Ad, cn.beckbi.pb.AdInfo.Ad.Builder, cn.beckbi.pb.AdInfo.AdOrBuilder>(
                  ads_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          ads_ = null;
        }
        return adsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AdList)
    }

    // @@protoc_insertion_point(class_scope:AdList)
    private static final cn.beckbi.pb.AdInfo.AdList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.beckbi.pb.AdInfo.AdList();
    }

    public static cn.beckbi.pb.AdInfo.AdList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AdList>
        PARSER = new com.google.protobuf.AbstractParser<AdList>() {
      public AdList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdList> getParserForType() {
      return PARSER;
    }

    public cn.beckbi.pb.AdInfo.AdList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AdIdListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AdIdList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 id = 1;</code>
     */
    java.util.List<java.lang.Integer> getIdList();
    /**
     * <code>repeated int32 id = 1;</code>
     */
    int getIdCount();
    /**
     * <code>repeated int32 id = 1;</code>
     */
    int getId(int index);
  }
  /**
   * Protobuf type {@code AdIdList}
   */
  public  static final class AdIdList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AdIdList)
      AdIdListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdIdList.newBuilder() to construct.
    private AdIdList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdIdList() {
      id_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdIdList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                id_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              id_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                id_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                id_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = java.util.Collections.unmodifiableList(id_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.beckbi.pb.AdInfo.internal_static_AdIdList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.beckbi.pb.AdInfo.internal_static_AdIdList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.beckbi.pb.AdInfo.AdIdList.class, cn.beckbi.pb.AdInfo.AdIdList.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> id_;
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getIdList() {
      return id_;
    }
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public int getIdCount() {
      return id_.size();
    }
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public int getId(int index) {
      return id_.get(index);
    }
    private int idMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getIdList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(idMemoizedSerializedSize);
      }
      for (int i = 0; i < id_.size(); i++) {
        output.writeInt32NoTag(id_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < id_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(id_.get(i));
        }
        size += dataSize;
        if (!getIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        idMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.beckbi.pb.AdInfo.AdIdList)) {
        return super.equals(obj);
      }
      cn.beckbi.pb.AdInfo.AdIdList other = (cn.beckbi.pb.AdInfo.AdIdList) obj;

      boolean result = true;
      result = result && getIdList()
          .equals(other.getIdList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getIdCount() > 0) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getIdList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.beckbi.pb.AdInfo.AdIdList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.beckbi.pb.AdInfo.AdIdList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.AdIdList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.beckbi.pb.AdInfo.AdIdList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.AdIdList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.beckbi.pb.AdInfo.AdIdList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.AdIdList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.beckbi.pb.AdInfo.AdIdList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.AdIdList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.beckbi.pb.AdInfo.AdIdList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.beckbi.pb.AdInfo.AdIdList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.beckbi.pb.AdInfo.AdIdList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.beckbi.pb.AdInfo.AdIdList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AdIdList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AdIdList)
        cn.beckbi.pb.AdInfo.AdIdListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.beckbi.pb.AdInfo.internal_static_AdIdList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.beckbi.pb.AdInfo.internal_static_AdIdList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.beckbi.pb.AdInfo.AdIdList.class, cn.beckbi.pb.AdInfo.AdIdList.Builder.class);
      }

      // Construct using cn.beckbi.pb.AdInfo.AdIdList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.beckbi.pb.AdInfo.internal_static_AdIdList_descriptor;
      }

      public cn.beckbi.pb.AdInfo.AdIdList getDefaultInstanceForType() {
        return cn.beckbi.pb.AdInfo.AdIdList.getDefaultInstance();
      }

      public cn.beckbi.pb.AdInfo.AdIdList build() {
        cn.beckbi.pb.AdInfo.AdIdList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.beckbi.pb.AdInfo.AdIdList buildPartial() {
        cn.beckbi.pb.AdInfo.AdIdList result = new cn.beckbi.pb.AdInfo.AdIdList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = java.util.Collections.unmodifiableList(id_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.beckbi.pb.AdInfo.AdIdList) {
          return mergeFrom((cn.beckbi.pb.AdInfo.AdIdList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.beckbi.pb.AdInfo.AdIdList other) {
        if (other == cn.beckbi.pb.AdInfo.AdIdList.getDefaultInstance()) return this;
        if (!other.id_.isEmpty()) {
          if (id_.isEmpty()) {
            id_ = other.id_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdIsMutable();
            id_.addAll(other.id_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.beckbi.pb.AdInfo.AdIdList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.beckbi.pb.AdInfo.AdIdList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> id_ = java.util.Collections.emptyList();
      private void ensureIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = new java.util.ArrayList<java.lang.Integer>(id_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getIdList() {
        return java.util.Collections.unmodifiableList(id_);
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public int getIdCount() {
        return id_.size();
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public int getId(int index) {
        return id_.get(index);
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public Builder setId(
          int index, int value) {
        ensureIdIsMutable();
        id_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public Builder addId(int value) {
        ensureIdIsMutable();
        id_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public Builder addAllId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, id_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public Builder clearId() {
        id_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AdIdList)
    }

    // @@protoc_insertion_point(class_scope:AdIdList)
    private static final cn.beckbi.pb.AdInfo.AdIdList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.beckbi.pb.AdInfo.AdIdList();
    }

    public static cn.beckbi.pb.AdInfo.AdIdList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AdIdList>
        PARSER = new com.google.protobuf.AbstractParser<AdIdList>() {
      public AdIdList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdIdList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdIdList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdIdList> getParserForType() {
      return PARSER;
    }

    public cn.beckbi.pb.AdInfo.AdIdList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ad_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Ad_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AdList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AdList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AdIdList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AdIdList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016proto/ad.proto\"B\n\002Ad\022\n\n\002id\030\001 \001(\005\022\014\n\004na" +
      "me\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\r\n\005price\030\004" +
      " \001(\002\"=\n\006AdList\022\020\n\010createAt\030\001 \001(\t\022\017\n\007trac" +
      "eId\030\002 \001(\t\022\020\n\003ads\030\003 \003(\0132\003.Ad\"\026\n\010AdIdList\022" +
      "\n\n\002id\030\001 \003(\0052P\n\010AdStream\022!\n\taddAdList\022\007.A" +
      "dList\032\t.AdIdList(\001\022!\n\tgetAdList\022\t.AdIdLi" +
      "st\032\007.AdList0\001B\026\n\014cn.beckbi.pbB\006AdInfob\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Ad_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Ad_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Ad_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Price", });
    internal_static_AdList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AdList_descriptor,
        new java.lang.String[] { "CreateAt", "TraceId", "Ads", });
    internal_static_AdIdList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AdIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AdIdList_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
